Switch to use metadata API instead of SQLAlchemy
Ensembl/ensembl-metadata-service pull request #25
Opened 2023-07-11 13:50 UTC by bilalebi

2023-09-07 13:57 UTC, marcoooo requested changes

2023-09-07 13:57 UTC, marcoooo commented on src/ensembl/__init__.py
> +#  See the NOTICE file distributed with this work for additional information
This file shouldn't exist to allow namespace packaging

2023-09-07 13:57 UTC, marcoooo commented on src/ensembl/production/__init__.py
> +#  See the NOTICE file distributed with this work for additional information
This file shouldn't exist to allow namespace packaging

2023-09-07 13:57 UTC, marcoooo commented on src/ensembl/production/metadata/__init__.py
> +#  See the NOTICE file distributed with this work for additional information
This file shouldn't exist to allow namespace packaging

2023-09-13 08:10 UTC, marcoooo commented on src/ensembl/production/metadata/__init__.py
Just to make sure, was this file retired? For compatibility with other namespaced packages.

2023-09-13 09:34 UTC, bilalebi commented on src/ensembl/production/metadata/__init__.py
> Just to make sure, was this file retired? For compatibility with other namespaced packages.

Yes, as you suggested [in this comment](https://github.com/Ensembl/ensembl-metadata-service/pull/25#discussion_r1318653936).
I don't mind putting it back as I don't see much difference (Am I missing something?)

2023-09-13 09:46 UTC, bilalebi commented on src/ensembl/production/metadata/__init__.py
@marcoooo, it's not there, as you can see here: https://github.com/Ensembl/ensembl-metadata-service/tree/chore/switch_to_md_api/src/ensembl/production/metadata

The `__init__.py` doesn't exist, even though it says _empty file_ as you described 🤷‍♂️

2023-09-13 10:55 UTC, marcoooo approved these changes

2023-09-19 07:07 UTC, merged